FROM ubuntu:18.04

RUN apt update -y \
    && apt install nginx -y \ 
    && apt-get install software-properties-common -y \
    && add-apt-repository ppa:certbot/certbot -y \
    && apt-get update -y \
    && apt-get install python-certbot-nginx -y \
    && apt-get clean

COPY  default.conf /etc/nginx/conf.d/default.conf

CMD ["nginx", "-g", "daemon off;"]