name: Publish to Docker

on:
  workflow_run:
    workflows: Linting And Testing
    types:
      - completed
    branches: [main]

jobs:
  publish:
    environment: Publish
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checking out branch
        uses: actions/checkout@v2

      - name: Build Images
        run: |
          docker build --build-arg NEXT_PUBLIC_SOCKET_URL=${{ secrets.NEXT_PUBLIC_SOCKET_URL }} -t rehanslife/scribble-client ./client
          docker build -t rehanslife/scribble-server ./server
          docker build -t rehanslife/scribble-nginx ./nginx               

      - name: Login to Docker
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_ID }} --password-stdin

      - name: Push Images to Docker
        run: |
          docker push rehanslife/scribble-client
          docker push rehanslife/scribble-nginx
          docker push rehanslife/scribble-server